language: java
sudo: false
script: mvn clean verify
services:
  - postgresql
before_script:
      - psql -c 'create database swvalerian;' -U postgres
      - psql -c "CREATE USER admin WITH PASSWORD 'admin';" -U postgres
flyway:
  enabled: false